services:
  - type: web
    name: xtrials-basement
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_PASSWORD
        generateValue: xtrials_basement_1337
